### ISSUE TITLE
conversion from energy response to photon response

### ISSUE THREAD

**Issue by gshennessy** [spacetelescope/pysynphot#105]
It is clear that with CCD's measuring photons instead of energy, the response curves of system throughput need to be changed. This is discussed in various places such as  Bessell and Murphy, Maiz Apellaniz, Casagrande and VandenBerg. 

Maiz Apellaniz DIVIDES by wavelength to convert from energy counting to photon counting. When I check the files in PYSYN_CDBS they seem to have been divided by wavelength and renormalized.

Bessell provides new filter responses where they seem to have been MULTIPLIED by wavelength.

Can someone clarify which is correct?

Thank  you.

**Comment by pllim** [comment]
@rizeladiaz , can someone from RedCat please answer this? Thanks.

**Comment by pllim** [comment]
Hello. This appears to be a question about the data files, which are not shipped with the software here. I would have to re-route you to https://stsci.service-now.com/hst . Please state which HST instrument you are interested in regarding this question, so it can be properly routed in the system. Thank you.
