### ISSUE TITLE
Include a warning if the ends of the bandpass are not zero.

### ISSUE THREAD

**Issue by eas342** [spacetelescope/pysynphot#112]
I love pysynphot but have been burned several times by noise in a bandpass. I suggest that a warning is thrown up if the ends of a bandpass are not zero because interpolation can drive dramatic changes in photometry. Here's an example:

```
import pysynphot as S
import numpy as np

sp = S.BlackBody(5e4)
w = np.array([44998,44999,45000,46000,47000,48000])
t = np.array([ 1e-3,  0.0,  1.0,  1.0,  1.0,  0.0])
bp = S.ArrayBandpass(w,t)

S.Observation(sp,bp,binset=sp.wave).effstim('mJy')
```
returns 121 mJy.

If a point is added at the beginning to zero out the bandpass, the result is very different.

```
w = np.array([44997,44998,44999,45000,46000,47000,48000])
t = np.array([  0.0, 1e-3,  0.0,  1.0,  1.0,  1.0,  0.0])
bp2 = S.ArrayBandpass(w,t)

S.Observation(sp,bp2,binset=sp.wave).effstim('mJy')
```
returns 10 mJy.

It would be helpful to put up a warning when the edges of a bandpass are not zero.

**Comment by pllim** [comment]
This isn't really a bug because PySynphot uses exactly what you provide. You can taper your bandpass with `taper()` method before using it.
