### ISSUE TITLE
Obsmode specification changing instrument rather than raising exception

### ISSUE THREAD

**Issue by tddesjardins** [spacetelescope/pysynphot#122]
Somehow the command `band(wfpc2,pc,f702w,cont#49581)` caused PySynphot (version 0.9.14) to switch the instrument from WFPC2 to WF/PC-1. The proper way to specify the PC chip is to use `band(wfpc2,1,f702w,cont#49581)`, which correctly selects the WFPC2 files from the master table. Incorrectly specifying the PC chip as "pc" instead of "1" in the obsmode selection should raise an exception rather than switching instruments.

**Comment by pllim** [comment]
Shouldn't this be fixed within TMG/TMC tables? PySynphot only parse them but does not impose any rules.

**Comment by tddesjardins** [comment]
But surely when it looks in the TMG, it needs to know which instrument to look up? Somehow it's mistakenly checking WF/PC-1 instead of WFPC2. If you do `band(wfpc2,pc,f702w)` and do showfiles(), it gives:

```
/grp/hst/cdbs/comp/ota/hst_ota_007_syn.fits
/grp/hst/cdbs/comp/wfpc/wfpc_optics_003_syn.fits
/grp/hst/cdbs/comp/wfpc/wfpc_f702w_003_syn.fits
/grp/hst/cdbs/comp/wfpc/wfpc_dqep6_005_syn.fits
```

**Comment by tddesjardins** [comment]
For clarification, `band(wfpc2,1,f702w)` correctly gives:

```
/grp/hst/cdbs/comp/ota/hst_ota_007_syn.fits
/grp/hst/cdbs/comp/wfpc2/wfpc2_optics_006_syn.fits
/grp/hst/cdbs/comp/wfpc2/wfpc2_f702w_006_syn.fits
/grp/hst/cdbs/comp/wfpc2/wfpc2_dqepc1_005_syn.fits
```

**Comment by pllim** [comment]
No, it is instrument agnostic. The implementation is in https://github.com/spacetelescope/pysynphot/blob/master/pysynphot/tables.py .

It completely relies on correctly specified lookup paths in the tables, as documented in https://pysynphot.readthedocs.io/en/latest/appendixc.html

**Comment by tddesjardins** [comment]
Hmm...if that's the case, @matt-mcmaster do you have any thoughts on how this could have happened via the TMG file?

**Comment by matt-mcmaster** [comment]
Yes.
wfpc2 IN=1 OUT=20
hst_ota IN=20 OUT=30
pc IN=30 OUT=3000
wfpc_optics IN=3000 OUT=3100
Then there are a bunch of clear/default COMPNAME/KEYWORD listings until you get to f702w

For wfpc2,1,f702w:
wfpc2 IN=1 OUT=20
hst_ota IN=20 OUT=30
wfpc2 IN=30 OUT=7000
wfpc2_optics IN=7000 OUT=7100
...and so on to get the rest of the obsmode.

Once 'pc' was specified in the obsmode, it switched the instrument via the INNODE/OUTNODE pairings to wf/pc-1.

On a side note, Brian York had written a script that traced every 'correct' path through the TMG as a means of checking something (I don't recall what it was offhand, I'd have to see if I can find it). Some of these 'correct' paths were quite interesting. I don't know if the information could be used to make a (mostly) foolproof TMG, but it might turn out to be a lot of work.

**Comment by tddesjardins** [comment]
Hmm....maybe some kind of sanity check could be written into the code that looks up the TMG table so that if the obsmode specification doesn't match names of the components in the table it throws an exception (or at least a warning).

**Comment by matt-mcmaster** [comment]
The list of obsmodes (it may not be complete) is attached to JIRA REDCAT-57 and is called 'obsmodes.txt'.  If the file were complete, and if it could somehow be incorporated into pysynphot, you could then determine if a given obsmode were valid or not. But it probably would be a lot of work.

**Comment by pllim** [comment]
PySynphot is not going to take new feature request, but feel free to open PR over at https://github.com/spacetelescope/stsynphot_refactor . I didn't change the table look-up algorithm in the port, except fixing some bugs.
