### ISSUE TITLE
Downloads do not unpack as expected

### ISSUE THREAD

**Issue by ivastar** [spacetelescope/pysynphot#136]
The download of synphot1.tar unpacked into grp/redcat/trds/comp/* while the code seemed to expect to find the comp/* directory. The error message is FileNotFound:

```
In [1]: import pysynphot as S
In [2]: bp = S.ObsBandpass('wfc3,ir,g141')
...
FileNotFoundError: [Errno 2] No such file or directory: '/Users/imomcheva/WORK/CRDS/comp/wfc3/wfc3_ir_primary_001_syn.fits'
```

Moving the comp directory to under CRDS fixes this.

**Comment by pllim** [comment]
1. Where did you download the tarball? Is it new from server or some old copy?
2. What is your PYSYN_CDBS set to?
