### ISSUE TITLE
Redshift flux inconsistent when flux unit is changed

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pysynphot#14]
I found the following behavior...
- Spectrum 1: Load in a spectrum, redshift (done in FLAM), convert to PHOTLAM.
- Spectrum 2: Load in a spectrum, convert to PHOTLAM, redshift (done in PHOTLAM).

The flux values in PHOTLAM for both are slightly different. You can reproduce as follows:

``` python
import pysynphot as S
import matplotlib.pyplot as plt

vega = S.Vega

sp1 = vega.redshift(0.03)  # FLAM
sp1.convert('photlam')  # PHOTLAM

sp2 = vega  # FLAM
sp2.convert('photlam')  # PHOTLAM  
sp2 = sp2.redshift(0.03)  # PHOTLAM

plt.plot(sp1.wave, sp1.flux, label='sp1')
plt.plot(sp2.wave, sp2.flux, label='sp2')
plt.xlim(1000, 15000)
plt.legend()
```

<img width="291" alt="untitled" src="https://cloud.githubusercontent.com/assets/2090236/17824109/128fdf5c-662e-11e6-9de4-0ca028b7873c.png">

c/c: @vglaidler

**Comment by ibusko** [comment]
I found there is still an issue here. The redshift method in pysynphot does not conserve flux, as in this example:

>>> vega = S.Vega
>>> delta = vega.wave[1:] - vega.wave[:-1]
>>> np.sum(vega.flux[1:] * delta)
2.9996953820230666e-05
>>> vega = vega.redshift(1.)
>>> delta = vega.wave[1:] - vega.wave[:-1]
>>> np.sum(vega.flux[1:] * delta)
15934849.59439772

If we use the correct units (redshifted flux is invariant only when expressed in photon units), then we get:

>>> vega = S.Vega
>>> delta = vega.wave[1:] - vega.wave[:-1]
>>> np.sum(vega.flux[1:] * delta)
2.9996953820230666e-05
>>> vega.convert('photnu')
>>> vega = vega.redshift(1.)
>>> vega.convert('flam')
>>> delta = vega.wave[1:] - vega.wave[:-1]
>>> np.sum(vega.flux[1:] * delta)
2.9996953820230666e-05

I think the units conversion should be included in the redshift method so it would enforce flux conservation.

**Comment by pllim** [comment]
@ibusko , it is a known issue that PySynphot redshift does not conserve flux. There were discussions on how to fix it but any fix was rejected for the sake of backward compatibility.

I did address this in the refactored version that uses Astropy (see spacetelescope/synphot_refactor#120). I offered many times to demo the refactored version but no one wants to use it. Ah, well.

**Comment by pllim** [comment]
Actually I am going to close this back. This should really be discussed as a separate issue.
