### ISSUE TITLE
issue with certain WFC3 spectral elements 

### ISSUE THREAD

**Issue by tumlinson** [spacetelescope/pysynphot#23]
This fails: 
> import pysynphot as S 
> bp = S.ObsBandpass('wfc3,uvis1,f225w')

[traceback below]

this happens even when the file in question is present in reference_files/comp/wfc3 and PYSYN_CDBS is set properly. 

I've tracked this as far back as _getFileNames in observationmode.py, where it appears that some elements are not having the path from $PYSYN_CDBS prepended to their filenames. As here: 

    def _getFileNames(self, comptable, compnames):
        files = []
        for compname in compnames:
            if compname not in [None, '', CLEAR]:
                index = N.where(comptable.compnames == compname)
                try:
                    iraffilename = comptable.filenames[index[0][0]]
                    print("INTHELOOP iraffilename",compname,iraffilename)
                    filename = irafconvert(iraffilename)
                    print("INTHELOOP     filename",compname,filename)
                    files.append(filename.lstrip())
                except IndexError:
                    raise IndexError("Can't find %s in comptable %s"%(compname,comptable.name))
            else:
                files.append(CLEAR)
        return files

The "INTHELOOP" lines show up at runtime like this: 
and note that wfc3uvis1_f225w_006_syn.fits does not have the path prepended. 
I suspect this is bug in locations.py but I'm not sure and thought I should report. 

INTHELOOP iraffilename hst_ota crotacomp$hst_ota_007_syn.fits
INTHELOOP     filename hst_ota /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/ota/hst_ota_007_syn.fits
INTHELOOP iraffilename wfc3_pom crwfc3comp$wfc3_pom_001_syn.fits
INTHELOOP     filename wfc3_pom /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_pom_001_syn.fits
INTHELOOP iraffilename wfc3_uvis_mir1 crwfc3comp$wfc3_uvis_mir1_002_syn.fits
INTHELOOP     filename wfc3_uvis_mir1 /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_uvis_mir1_002_syn.fits
INTHELOOP iraffilename wfc3_uvis_mir2 crwfc3comp$wfc3_uvis_mir2_002_syn.fits
INTHELOOP     filename wfc3_uvis_mir2 /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_uvis_mir2_002_syn.fits
INTHELOOP iraffilename wfc3uvis1_f225w wfc3uvis1_f225w_006_syn.fits
INTHELOOP     filename wfc3uvis1_f225w wfc3uvis1_f225w_006_syn.fits
INTHELOOP iraffilename wfc3_uvis_owin crwfc3comp$wfc3_uvis_owin_002_syn.fits
INTHELOOP     filename wfc3_uvis_owin /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_uvis_owin_002_syn.fits
INTHELOOP iraffilename wfc3_uvis_iwin crwfc3comp$wfc3_uvis_iwin_002_syn.fits
INTHELOOP     filename wfc3_uvis_iwin /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_uvis_iwin_002_syn.fits
INTHELOOP iraffilename wfc3_uvis_ccd1 crwfc3comp$wfc3_uvis_ccd1_003_syn.fits
INTHELOOP     filename wfc3_uvis_ccd1 /Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/reference_files/comp/wfc3/wfc3_uvis_ccd1_003_syn.fits
INTHELOOP iraffilename wfc3uvis1_cor wfc3uvis1_cor_004_syn.fits
INTHELOOP     filename wfc3uvis1_cor wfc3uvis1_cor_004_syn.fits

TRACEBACK: 

----> 1 bp = S.ObsBandpass('wfc3,uvis1,f225w')

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/obsbandpass.pyc in ObsBandpass(obstring, graphtable, comptable, component_dict)
     42     ##ObsModeBandpass or a TabularSpectralElement will be returned.
     43     ob=ObservationMode(obstring,graphtable=graphtable,
---> 44                        comptable=comptable,component_dict=component_dict)
     45     if len(ob) > 1:
     46         return ObsModeBandpass(ob)

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/observationmode.py in __init__(self, obsmode, method, graphtable, comptable, component_dict)
    326 
    327         self.components = self._getOpticalComponents(self._throughput_filenames,
--> 328                                                       component_dict)
    329 
    330 

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/observationmode.py in _getOpticalComponents(self, throughput_filenames, component_dict)
    342             else:
    343               component = _Component(throughput_name,
--> 344                                      interpval=self.pardict.get(parkey))
    345               component_dict[(throughput_name, self.pardict.get(parkey))] = component
    346 

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/observationmode.py in __init__(self, throughput_name, interpval)
    617         self._empty = True
    618 
--> 619         self.throughput = self._buildThroughput(throughput_name, interpval)
    620         if self.throughput is not None:
    621             self.waveunits = self.throughput.waveunits

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/observationmode.py in _buildThroughput(self, name, interpval)
    628             if interpval is None:
    629                 self._empty = False
--> 630                 return spectrum.TabularSpectralElement(name)
    631             else:
    632                 self._empty = False

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/spectrum.pyc in __init__(self, fileName, thrucol)
   2737             if fileName.endswith('.fits') or fileName.endswith('.fit'):
   2738                 print("  ")
-> 2739                 self._readFITS(fileName, thrucol)
   2740             else:
   2741                 self._readASCII(fileName)

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/pysynphot/spectrum.pyc in _readFITS(self, filename, thrucol)
   2775 
   2776     def _readFITS(self,filename,thrucol='throughput'):
-> 2777         fs = pyfits.open(filename)
   2778 
   2779         # pyfits cannot close the file on .close() if there are still

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.pyc in fitsopen(name, mode, memmap, save_backup, cache, **kwargs)
    137         raise ValueError('Empty filename: %s' % repr(name))
    138 
--> 139     return HDUList.fromfile(name, mode, memmap, save_backup, cache, **kwargs)
    140 
    141 

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.pyc in fromfile(cls, fileobj, mode, memmap, save_backup, cache, **kwargs)
    279 
    280         return cls._readfrom(fileobj=fileobj, mode=mode, memmap=memmap,
--> 281                              save_backup=save_backup, cache=cache, **kwargs)
    282 
    283     @classmethod

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.pyc in _readfrom(cls, fileobj, data, mode, memmap, save_backup, cache, **kwargs)
    800             if not isinstance(fileobj, _File):
    801                 # instantiate a FITS file object (ffo)
--> 802                 ffo = _File(fileobj, mode=mode, memmap=memmap, cache=cache)
    803             else:
    804                 ffo = fileobj

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/file.pyc in __init__(self, fileobj, mode, memmap, clobber, cache)
    148             self._open_fileobj(fileobj, mode, clobber)
    149         elif isinstance(fileobj, string_types):
--> 150             self._open_filename(fileobj, mode, clobber)
    151         else:
    152             self._open_filelike(fileobj, mode, clobber)

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/file.pyc in _open_filename(self, filename, mode, clobber)
    500             self._file = bz2.BZ2File(self.name, bzip2_mode)
    501         else:
--> 502             self._file = fileobj_open(self.name, PYFITS_MODES[mode])
    503 
    504         # Make certain we're back at the beginning of the file

/Users/tumlinson/yt-conda/lib/python2.7/site-packages/astropy/io/fits/util.pyc in fileobj_open(filename, mode)
    401         """
    402 
--> 403         return open(filename, mode)
    404 
    405 

IOError: [Errno 2] No such file or directory: 'wfc3uvis1_f225w_006_syn.fits'

**Comment by pllim** [comment]
There was a problem with CDBS files where one of the `mtab` tables was incorrect. Are you using the latest TMG/TMC/TMT files?

**Comment by tumlinson** [comment]
Hi Pey-Lian, 
I did indeed have old TMG/TMC/TMT files, from April. I didn't think to do this since I had just installed a fresh pysynphot. But it works now. Thanks.

**Comment by pllim** [comment]
pysynphot is just the software, it does not manage the HST data files; CDBS manages them. Glad it works now.
