### ISSUE TITLE
Error with ObsBandpass function

### ISSUE THREAD

**Issue by SiqiLiu-647** [spacetelescope/pysynphot#26]
Hi, I met a problem with ObsBandpass function. For the examples given in the document: 
`bp_v = S.ObsBandpass('johnson,v')` 
it returns a TypeError: 
`TypeError: initializing GraphTable with GFile=None; possible bad/missing CDBS.`
I was wondering if anyone have idea on how this could be solved... Thanks!

**Comment by pllim** [comment]
You need to download the data files and point PySynphot to where you store them. See https://pysynphot.readthedocs.io/en/latest/#installation-and-setup .

**Comment by HeloiseS** [comment]
Hello,

I'm running in the same error but ONLY when Im running python 3.7. I've go the pysonphot data and added the environment to my data path - any idea what might be going on?

(linux machine with ubuntu 18.04)
