### ISSUE TITLE
Update code to deal with removed 'new_table' from astropy.io.fits

### ISSUE THREAD

**Issue by mcara** [spacetelescope/pysynphot#27]
``new_table()`` function has been removed from ``astropy.io.fits`` starting with version 1.3 (see commit https://github.com/astropy/astropy/commit/1c3e876b935951c716ef53cbf41db9b889de6b2d). The code in ``pysynphot`` needs to be updated to accommodate above mentioned changes.

**Comment by pllim** [comment]
Fixed in #28.
