### ISSUE TITLE
Discontinuous pysynphot.Vega spectrum

### ISSUE THREAD

**Issue by gastronomyk** [spacetelescope/pysynphot#3]
Dear pysynphot team,

there seem to be several discontinuities in the standard Vega spectrum provided - around 3000 A and 5500 A. Is this normal? As a comparison, the spectrum of an A0V star from the pickles library doesn't have these large jumps. 
```
S = importlib.reload(pysynphot)
plt.semilogy(S.Vega.wave, S.Vega.flux)
plt.ylim(1E7, 1E9)
plt.xlim(1000, 15000)
```
![image](https://cloud.githubusercontent.com/assets/9432898/14882474/4e12f76a-0d39-11e6-87be-f7544a7d4953.png)

My pysynphot installation is fresh, having followed the instructions on readthedocs - http://pysynphot.readthedocs.io/en/latest/index.html. Everything else works fine.

Cheers,
Kieran

P.S. Thanks for creating the package, it's super useful!

**Comment by pllim** [comment]
@gastronomyk , just to be sure we're on the same page, please provide print out for the following:

```python
>>> import pysynphot as S
>>> print S.__version__
```

**Comment by gastronomyk** [comment]
@pllim 
```
>>> print S.__version__
0.9.8.2.dev
```
I also just saw the sentence
"pysynphot is not fully tested under Python 3. Please use Python 2.7."
I've been using Python 3.4 until now. Could that have something to do with it?

**Comment by pllim** [comment]
@gastronomyk , my colleague and I both cannot reproduce your result in Python 2. I'll see if I can reproduce in Python 3.

```python
>>> import matplotlib.pyplot as plt
>>> import pysynphot as S
>>> S.__version__
'0.9.8.2.dev'
>>> S.Vega.name
'.../lib/python2.7/site-packages/pysynphot-0.9.8.2.dev0-py2.7-linux-x86_64.egg/pysynphot/data/alpha_lyr_stis_008.fits'
>>> plt.semilogy(S.Vega.wave, S.Vega.flux)
>>> plt.xlim(1000, 15000)
>>> plt.ylim(1e-11, 1e-7)
```

![figure_1](https://cloud.githubusercontent.com/assets/2090236/14896639/ad5cebb4-0d4c-11e6-99fa-28f9182168a9.png)

**Comment by pllim** [comment]
Just tested in Python 3.5.1. I still don't see the jump.

![figure_1](https://cloud.githubusercontent.com/assets/2090236/14897107/ac259460-0d4e-11e6-9960-10cbecddb91f.png)

**Comment by pllim** [comment]
Underlying computations use Numpy and the file is read in with Astropy. What are your Numpy and Astropy versions?

**Comment by gastronomyk** [comment]
Hi @pllim,

this morning I also couldn't reproduce the jumps straight off, then I realised I was using photon counts yesterday, rather than Flam. When plotting in Flam and Fnu, Vega's spectrum is fine - it's only when using `.convert("count")` that the discontinuities appear:

![image](https://cloud.githubusercontent.com/assets/9432898/14909599/dcee7354-0de5-11e6-909c-340851a71e93.png)

Here's the code from my jupyter notebook
```
import matplotlib.pyplot as plt
%matplotlib inline
plt.figure(figsize=(15,5))

import pysynphot
S = importlib.reload(pysynphot)
vega = S.Vega

plt.subplot(131)
vega.convert("Flam")
plt.semilogy(vega.wave, vega.flux)
plt.ylim(1E-10, 1E-8)
plt.xlim(1000, 15000)
plt.title("Flam", fontsize=18)

plt.subplot(132)
vega.convert("count")
plt.semilogy(vega.wave, vega.flux)
plt.ylim(1E7, 1E9)
plt.xlim(1000, 15000)
plt.title("counts", fontsize=18)

plt.subplot(133)
vega.convert("Fnu")
plt.semilogy(vega.wave, vega.flux)
plt.ylim(1E-21, 1E-19)
plt.xlim(1000, 15000)
plt.title("Fnu", fontsize=18)`
```

Also to answer your previous question, my astropy and numpy version:
```
>>> import astropy
>>> print("Astropy:", astropy.__version__)
Astropy: 1.1.2
>>> import numpy
>>> print("Numpy:", numpy.__version__)
Numpy: 1.10.4
```

**Comment by pllim** [comment]
@gastronomyk , `counts` by itself is not very useful. It depends on telescope collecting area and detector binning. When you convert like that, it uses HST area and default wavelength set as detector bins, which does not make much physical sense. The proper way to use `counts` is to first create an `Observation` using the HST detector of your choice.

**Comment by pllim** [comment]
Here is a more detailed explanation from @philhodge 
<hr/>

This is the problem:
```python
>>> vega.convert("count")
>>> wl = vega.wave
>>> flux = vega.flux
>>> # index, wavelength, delta_wavelength, counts:
>>> for i in range(1675, 1681):
...     print("{} {:.3f} {:.4f}  {:.1f}".format(i, wl[i], (wl[i+1] - wl[i]), flux[i]))
...
1675  3060.378 1.3699  33854880.2
1676  3061.748 1.3699  34295080.8
1677  3063.118 1.3699  34329538.4
1678  3064.488 2.7588  51665292.5
1679  3067.247 2.7458  67800186.0
1680  3069.993 2.7458  67709039.5
```

It appears that "count" means counts within the current wavelength bin. It's the size of the wavelength bin that's discontinuous. There's a similar discontinuity in the wavelength spacing near index 2509.

**Comment by pllim** [comment]
@gastronomyk , I think this issue has been sufficiently explained. If you feel otherwise, feel free to re-open. Thanks.

**Comment by gastronomyk** [comment]
@pllim, @philhodge - Thanks very much for the detailed explanations and effort on your behalf. Very much appreciated. The different wavelength bin sizes makes sense and I've changed my code to take that into account. Cheers!
