### ISSUE TITLE
Warning when importing pysynphot

### ISSUE THREAD

**Issue by mdastro** [spacetelescope/pysynphot#34]
Hello,

I am trying to use pysynphot to simulate photometric data from a certain set of filters and I get the following warning when I import it:
```
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:44: UserWarning: PYSYN_CDBS is undefined; functionality will be SEVERELY crippled.
>   warnings.warn("PYSYN_CDBS is undefined; functionality will be SEVERELY "
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:119: UserWarning: Extinction files should be moved to $PYSYN_CDBS/extinction for compatibility with future versions of pysynphot.
>   warnings.warn('Extinction files should be moved to '
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:155: UserWarning: Extinction files not found in grid/extinction
>   warnings.warn('Extinction files not found in %s' % (extdir,))
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:133: UserWarning: PYSYN_CDBS is undefined; cannot find mtab/*_tmg.fits file
>   warnings.warn("PYSYN_CDBS is undefined; cannot find %s file" % template)
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:133: UserWarning: PYSYN_CDBS is undefined; cannot find mtab/*_tmc.fits file
>   warnings.warn("PYSYN_CDBS is undefined; cannot find %s file" % template)
> /home/mldantas/miniconda2/lib/python2.7/site-packages/pysynphot/locations.py:133: UserWarning: PYSYN_CDBS is undefined; cannot find mtab/*_tmt.fits file
>   warnings.warn("PYSYN_CDBS is undefined; cannot find %s file" % template)
```
I was in doubt if I should or not open an issue, so I am sorry if I shouldn't. It would be very kind if someone could help me with this warning.

Thank you!

Regards,

Maria Luiza

**Comment by mdastro** [comment]
PS. I forgot to mention that pysynphot does not work on 2 of my machines (desktop and laptop) and I believe it is linked to the warning aforementioned.

**Comment by pllim** [comment]
Following http://pysynphot.readthedocs.io/en/latest/#installation-and-setup should resolve your issue. If that is the case, please close this.

**Comment by mdastro** [comment]
Hi @pllim,

Thanks for your answer, I realized that I hadn't followed the steps in downloading and setting the files as described after the pip install part. 
However, after doing that, only some IDEs manage to import pysynphot (which, for practical matters, is just fine), others fail to find it. It may be an useful information for possible future improvements.

Thank you very much for pointing that to me.

Kind regards,

Maria Luiza

**Comment by pllim** [comment]
Regarding why some IDEs don't work with pysynphot, I need more information, like exact product names, versions, commands you used, and warning/error/traceback messages. You can open a new issue for that. Thank you.

**Comment by mdastro** [comment]
Hello @pllim , I will then open such issue. I have also a few questions on how to use pysynphot which I can't find in the documentation (pdf and website), neither by reading the docstring. Would you mind if I asked you a few simple questions? If yes, how do you prefer me to do it (an issue to be tagged as question or e-mail...)?
Thanks again!

**Comment by pllim** [comment]
@mdastro , I would prefer one GitHub issue per question if your questions are not related to each other (e.g., IDE import error and usage of specific function are separate issues).

Alternately, you can contact `help[at]stsci.edu` directly. In that case, you do not have to separate them.

**Comment by mdastro** [comment]
Sure @pllim, thanks. Will do.
