### ISSUE TITLE
Pysynphot installation works differently among IDEs

### ISSUE THREAD

**Issue by mdastro** [spacetelescope/pysynphot#35]
Hello,

I have successfully installed pysynphot and I manage to import it using directly python in the command line,   ipython, and jupyter notebook. However, when using PyCharm (version 5), it does not recognize pysynphot. I reinstalled it using PyCharm's options (see top menu >> File >> Settings):

![pysynphot02](https://cloud.githubusercontent.com/assets/10452764/24722523/605541be-1a1a-11e7-822a-d2da9309d808.png)

But the process required before (as described here: http://pysynphot.readthedocs.io/en/latest/#installation-and-setup) is ignored and the error reported in [issue 34 ](https://github.com/spacetelescope/pysynphot/issues/34) happens. It is probably something linked to "where" is PyCharm is "looking at" to process the package. 

I have been trying implement it in PyCharm but with no success so far.

Thank you!

**Comment by pllim** [comment]
Thank you for the report. PyCharm usage is not supported and I have no plans to do so. Please use it in a Python, IPython, or Jupyter Notebook.

**Comment by mdastro** [comment]
Ok, thank you @pllim .
