### ISSUE TITLE
Simulated photometry does not agree with original spectrum

### ISSUE THREAD

**Issue by mdastro** [spacetelescope/pysynphot#38]
Hi @plimm,

I have used pysynphot to generate several simulated photometries for 2 surveys, one with 59 narrow-filter bands and another one with 12. The simulated photometry not always agree with the original spectrum like the above images:
![1665 52976 514_jpas](https://cloud.githubusercontent.com/assets/10452764/25900191/fb329556-3568-11e7-8883-90d0cc06db98.png)

Please note the first bands, how different from the spectrum they are.

![0443 51873 152_jplus](https://cloud.githubusercontent.com/assets/10452764/25900200/052a2b6e-3569-11e7-8ba7-b34d92d31341.png)

Please note the last bands.

I have performed a chi^2 ajustment (of course, checked it without it) and I have no clue why this difference happens. I don't know if this is something from pysynphot or not. All in all, it works fine, except for some filters.

If you need a reproducible example, please let me know, I can provide a very didactic jupyter notebook.

Thank you very much once again.

Cheers.

**Comment by pllim** [comment]
Check the filter sampling and your observation binning. Also, what were the exact commands you used to produce your PySynphot results? The interpolation is only as good as the data you gave the software.

**Comment by pllim** [comment]
Also, what do you mean by the "original spectrum"? If you convolve the "original spectrum" with a filter, of course it is not going to look the same anymore. Please clarify.

**Comment by mdastro** [comment]
Hi @pllim , sorry for the delay in answering you. I was in a workshop these past two weeks and couldn't test the spectra, which I will do now. By "original spectrum" I mean the spectrum from which I created the photometry. Let me check these results again and get back to you.

**Comment by mdastro** [comment]
Hi @pllim ,

I checked the binning of both the spectra and the filters and they are all binned at 1 Angstrom. I am a bit reluctant in making a new jupyter notebook to explain the problem, because it would be a bit complicated. If there is no other way, I will do it. For the moment, you can see exactly what I am doing here: https://github.com/mdastro/Challenge/blob/master/Coding/sanity_check_jpas.ipynb

In the jupyter notebook above you can see the commands I use in pysynphot. The input files are the following: 

- the filters which I refer to in there can be found here: https://github.com/mdastro/Challenge/tree/master/Filters/JPAS_Filters
- the spectra here: https://github.com/mdastro/Challenge/tree/master/SanityCheck/Spectra
- the specs_list: https://github.com/mdastro/Challenge/blob/master/SanityCheck/specslist2.txt
- the filters_list: https://github.com/mdastro/Challenge/blob/master/Filters/jpas_filters_list.txt 

I hope this is enough. If you need anything else, please let me know.

Thanks for your help once again and sorry for my delay and keeping this up.

Cheers!

**Comment by pllim** [comment]
The plots in your notebook are different from the ones you originally reported. Which files did you use for the original plots?

**Comment by mdastro** [comment]
The notebook has the first original plot. The second one was a result from other filters, which I didn't include in the notebook, just to be simpler. I believe the cause of this difference is the same.

**Comment by mdastro** [comment]
The 2 images were just examples of the problem I have in hands with several other spectra. For instance:

This result is perfect -- it is using the filters I ommitted in that notebbok.
![1019 52707 261_jplus](https://cloud.githubusercontent.com/assets/10452764/26649918/0f32df14-461e-11e7-9d86-552eae6355cc.png)

This isn't. :/ This problem also appears in the notebook I sent you.
![1019 52707 261_jpas](https://cloud.githubusercontent.com/assets/10452764/26649917/0f329054-461e-11e7-9de0-baf057b502cd.png)

**Comment by pllim** [comment]
Can you please give me the following?

* 1 good filter
* 1 bad filter

That would save me a lot of time. Thanks.

**Comment by mdastro** [comment]
Hi @pllim ,

The good filters and bad filter vary from object to object. I could give you a specific example of one object and the filters that are good and bad for this specific case.  Would that be ok?

Cheers!

**Comment by pllim** [comment]
Yes, that would be perfect. Thank you!

**Comment by mdastro** [comment]
Hi @pllim 

I was starting to think I would never have the time to properly answer you! Sorry for that.
I finally created the notebook I promised, with one spectrum and 2 filters, one good and one bad.
The folder with everything needed is here:
https://github.com/mdastro/Challenge/tree/master/Simplest_Pysynphot/FiltersTest

The notebook is this one:

https://github.com/mdastro/Challenge/blob/master/Simplest_Pysynphot/FiltersTest/Filter%20Test.ipynb

I appreciate any help you can give me.

Thank you!

**Comment by mdastro** [comment]
PS.: by the way, I tried to rebin the spectrum by 0.1A (and even by 0.01 -- originally it is 1A), but the results remain the same. I added the rebinned spec by 0.1A in the folder I mentioned above.

**Comment by pllim** [comment]
Thank you very much, @mdastro ! I will have a look and get back to you soon.

**Comment by pllim** [comment]
It turns out your "bad" filter covers a spectrum region where its flux dropped off to zero. I was able to "hack" the spectrum to give a "correct" photometry as follows (although modifying source spectrum like this is not recommended unless you understand why its flux dropped to zero and is okay with extrapolating over zero-flux region with the nearest non-zero flux value):
```python
import pysynphot as S
# And same setup as your Jupyter notebook
sp = spectrum
i = np.where(sp.flux > 0)
sp2 = S.ArraySpectrum(wave=sp.wave[i], flux=sp.flux[i],
                      fluxunits=sp.fluxunits, waveunits=sp.waveunits)
obs2 = S.Observation(sp2, jplus_bad_filter, binset=binset, force='extrap')
phot_obs2 = obs2.effstim('flam')
lamb_obs2 = obs2.efflam()
# ax2 here is the matplotlib axis I have previously created, you can use plt as you did
ax2.plot(lamb_obs2, phot_obs2, '*', color='red', markersize=10, label='badfixed')
```

![figure_2](https://user-images.githubusercontent.com/2090236/27655247-bdc36e7c-5c12-11e7-8ee0-737cca65e9f0.png)

I suspect the other affected filters have the same problem. The two "bad" points around 6000 and 7000 Angstrom, respectively, in your first plot above might have come from very broad filters that somehow extends to the zero-flux region as well.

If this sufficiently answers your question, please close the issue. Thank you for your patience!

**Comment by mdastro** [comment]
Hi @pllim ,

Thank you for that. I suspected something like that, but it seems weird with so many point (i.e. see the first image in this issue).
However, I will try your solution and if it works perfectly, I will close this issue.

Thank you very much!!!

**Comment by pllim** [comment]
As for the first image, most of the bad points are near edges (except those two around 6000 and 7000 Angstroms that I pointed out), so nothing too surprising there. In addition, the flux drops to zero much later after 3000 Angstrom, which is the starting point of your `binset`.

I think the easiest way for your do test my theory is to make copies of those spectrum. In the copies of the spectrum files, strip out *all* rows with zero-flux. Then re-run your analysis as-is.

**Comment by mdastro** [comment]
Yes, that's right.
Could you just tell me which binset you used (it is binset=binset) just to avoid errors in the test I am doing. :)
Thanks!

**Comment by pllim** [comment]
Ops, sorry. `binset = np.arange(3000, 11000)` as you had in your notebook. I simply stored it in a variable to avoid redundant computation.

**Comment by mdastro** [comment]
thanks!

**Comment by mdastro** [comment]
So @pllim , I incorporated your improvement in the code, but mysteriously it hasn't changed the results. I updated the jupyter notebook: https://github.com/mdastro/Challenge/blob/master/Simplest_Pysynphot/Photometry%20Simulation.ipynb
Could you please take a look at it?
I tried cleaning the kernel, but this wasn't it. Sorry for giving you so much trouble.
Thanks again!

**Comment by mdastro** [comment]
Sorry, it is actually where it was before, here:
https://github.com/mdastro/Challenge/blob/master/Simplest_Pysynphot/FiltersTest/Filter%20Test.ipynb

**Comment by pllim** [comment]
That does not make sense. Try a new Jupyter notebook session (kill the server and restart)? Also print out `sp2.flux`, `phot_obs2`, and `lamb_obs2`.

**Comment by mdastro** [comment]
Will do




Maria Luiza Linhares Dantas
[image: https://]about.me/mdantas.astro
<https://about.me/mdantas.astro?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api>

PhD Candidate
Astronomy Department - IAG-USP - Brazil
goo.gl/xQy4Ur

2017-06-28 17:21 GMT-03:00 P. L. Lim <notifications@github.com>:

**Comment by mdastro** [comment]
It's really weird @pllim , when I print them, they appear almost as if I hand't forced that sp.flux >0 !!!
When I print the bad photometry and effective wavelength I have:

```
print photometry_bad_flam
print lambda_eff_bad
print sdss_spectrum.flux.shape
3.85719286331e-16
7516.30368089
(60000,)
```

When I print the the new one that should work I get:

```
print phot_obs2
print lamb_obs2
print sp2.flux.shape
3.8571928694e-16
7516.30368248
(47560,)
```

I am still trying to figure out why this is not working in my code. :/

**Comment by pllim** [comment]
I really don't know why it does not work for you. I have posted my own notebook of your use case at https://gist.github.com/pllim/bfd81183766774cef72f17fc45094903 . Try run that exactly as given and see if you get the same things as I do.

**Comment by mdastro** [comment]
Thanks so much, I will check it and see what may be the problem.

**Comment by mdastro** [comment]
@pllim , the creepiest thing just happened, I downloaded your python notebook and the **only** thing I changed was the path to the files and still the photometry does not match.
Plus, even the version of pysynphot is the same...

I have no idea what is going on.
I am going to try to generate a new spectrum without the zeroes and see if this makes a difference.

You can see it here: https://github.com/mdastro/Challenge/blob/master/Simplest_Pysynphot/FiltersTest/PySynphot_Issue_38.ipynb

**Comment by mdastro** [comment]
Forget everything, it worked now perfectly. I realized I was testing with the rebinned sample and for some reason it was still problematic! I updated it and now it is working!!!

**Comment by pllim** [comment]
Great news! Thanks for letting me know.

**Comment by mdastro** [comment]
Hi @pllim ,

Sorry for reopening this issue, I will explain why.

Although the example we ran together worked perfectly, when I applied it to the real case, some photometries still show problems.

Let me try to expose what is going on, I guess you already understood that I am trying to simulate photometry of 2 ("sibling") surveys (one is called J-PAS and the other J-PLUS) from SDSS spectra. Both are photometric surveys. The first one is composed of 56 narrow-band and 3 broad-band filters (something like that); and the second of 8 narrow-band filters and 5 broad-band (Sloan-like, ugriz) -- see http://j-pas.org/survey/survey and http://j-plus.es/survey.

So, now,  you helped me solve many of the issues I had from the beginning, the simulation with J-PLUS looks fine (the one with less filters). See new notebook here:
https://github.com/mdastro/Challenge/blob/master/Coding/sanity_check_jplus.ipynb
(ignore the image in the middle, that one has other problems, I put a "try" and "except" just to make the code run for all objects).

But the J-PAS still has problems, although it looks much better now:
https://github.com/mdastro/Challenge/blob/master/Coding/sanity_check_jpas.ipynb
The steps of this notebook are similar, I just did some changes step by step to see what was going on. When I apply Chi^2 minimization, it becomes a bit better, but still has problems.

I customized the binset with the maximum and minimum values of the wavelengths for each object, which is probably the right way to do it.

Just for comparison, I will show cases from "before" the flux>0 correction and they are now.

This is what happened with the object in the first image I put in this issue:
![1665 52976 514_jpas](https://user-images.githubusercontent.com/10452764/27714277-52bb1752-5d06-11e7-9bb5-4a4c926377e1.png)
It still has problems.

This is the second and looks good:
![1665 52976 514_jplus](https://user-images.githubusercontent.com/10452764/27714317-7a0a67a4-5d06-11e7-8935-a16761f87c06.png)

Do you have any idea of what can be wrong?
Do you think that the narrow filters can be problematic for the integration?
Should I rebin the spectra? :/

Thanks once again!

**Comment by pllim** [comment]
The main problem is your source spectra are cut off at specific wavelengths. PySynphot cannot recreate lost data, the best it can do it extrapolate via nearest point, which might not suit your needs. Why are they cut off? Can you find complementary observation to fill in the lost data?

If you want to pursue the remaining "bad" points, you will have to provide me the exact files for those. I would say one filter for that point around 6000 Angstrom and one around 4500 Angstrom (from your first plot above). I don't think this is a software bug, but simply the need to understand what the software is doing to your data.

**Comment by mdastro** [comment]
You are totally right. I agree that this is a matter of understanding what is going on.
What do you mean by cut at specific wls? Do you mean that the spectra aren't continuous or that there are these edges with flux=0?

**Comment by pllim** [comment]
> Do you mean that the spectra aren't continuous or that there are these edges with flux=0?

I mean the edges are sudden drop-downs to zero flux; They don't look very physical, in the sense that you won't see something like that naturally (without filter or with indefinitely wide filter).

**Comment by mdastro** [comment]
Yes, it's true. These edges just mean that there are no observations there. So, I should perhaps run a code to remove these edges. That should work, right?

**Comment by pllim** [comment]
That depends. Like I said, if you simply remove zero-flux region, PySynphot is simply going to extrapolate using the nearest point. If such approximation does not sufficiently represent the actual spectrum (e.g., what if the spectrum has a lot of emission features around 3000 Angstrom?), then PySynphot will *underestimate* the photometry, as you have seen.

**Comment by mdastro** [comment]
I see @pllim . But let me try to understand something, why does it work well with broader bands and not so well with narrow bands?
I think these things are not random, I think there's a connection, because the results are systematically good for large filters whereas can be confusing for straight ones. The first example of bad results I sent you yesterday (image with the filters plotted), the photometries in lower wls are systematically underestimated, but when we look are higher wls, it's just fine. would that be because of this "plateau" in the spectrum?

What would you do if you had to solve this problem? I thought about using a ratio of the differences in order to multiply by such factor in order to correct it. What do you think?

**Comment by pllim** [comment]
> I think there's a connection

I agree. But I need a specific case to investigate further. If you give me the spectrum file (which seems to be a different one from what you gave me before) and the narrowband filter that is still problematic, then I can have a look. Perhaps it is simply small-number statistics problem but it is just a guess until I can look at the data.

> What would you do if you had to solve this problem?

That is a science question, which is not for me to answer, as I am not involved nor understand the full scope of your research goals. Ideally, from the software point of view, the result would be most accurate if you can provide a spectrum that is not cut off like that.

**Comment by mdastro** [comment]
> Perhaps it is simply small-number statistics problem but it is just a guess until I can look at the data.
Ok, I will try to give you an example ASAP

**Comment by pllim** [comment]
Sorry if I wasn't clear. I only need *one* of the problematic narrowband. Could you please include that in your "FiltersTest" directory? Thank you!

**Comment by mdastro** [comment]
Sorry for the mistake!
I added 2 filters that are bad in both spectra (if I didn't make any mistake) and they are under the extension .res which is just a txt file.
Let me know if you need anything else. :)

**Comment by pllim** [comment]
Thank you for the files. I have no problem getting the photometry to agree, see https://gist.github.com/pllim/65dcd8f23715ab859ef39340077f9233 .

The issue here is that these test cases are *very* sensitive to `binset`, probably because the filters are narrow *and* also sampling a "busy" area of the spectrum (not to mention low flux and the extrapolated edge). When I set the `binset` to be the filter's wavelength set, things appear alright. So my advice for your remaining "bad" filters is to use the individual filter's wavelength set for `binset`; and if that does not work, define a custom `binset` that is optimal for that particular filter (if you don't know what that is, try asking the instrument specialists).

**Comment by mdastro** [comment]
That's great, @pllim ! I will try your solution ASAP and get back to you.

**Comment by mdastro** [comment]
@pllim , your suggestion was great. It almost (sigh!) completely solved my problems! The simulated photometry looks way better, but there is still a fine tuning to be made, probably also because of the narrow filters. You are right, pysynphot is really sensitive to the binset for narrow bands.

There are 2 cases that are still a bit weird though.

# Case 1

![1180 52995 637_jpas](https://user-images.githubusercontent.com/10452764/27764458-6a615afe-5e70-11e7-86ee-308beeb34c38.png)

For some reason, after a certain WL, the simulated photometry just jumps and stays in this sort of plateau. I don't worry much about this object because it has problems, warnings, etc. However, there is still another case...


 # Case 2
![2231 53816 545_jpas](https://user-images.githubusercontent.com/10452764/27764486-f05a55f2-5e70-11e7-906f-387349e15a62.png)

The first photometries of this object are a bit shifted from the spectrum. I will add this spectrum in that folder you like (https://github.com/mdastro/Challenge/tree/master/Simplest_Pysynphot/FiltersTest) as well as 2 or 3 bands. Would you mind taking look at it?

Thank you so much!

**Comment by mdastro** [comment]
You can totally forget bour #case 1 because this plateau is an error, because the flux=0 in those points. When I remove them:
![1180 52995 637_jpas](https://user-images.githubusercontent.com/10452764/27764607-9f6ee132-5e73-11e7-91e2-39a123be2111.png)

But Case 2 is a bit strange still...
![2231 53816 545_jpas](https://user-images.githubusercontent.com/10452764/27764610-aa59b16c-5e73-11e7-844c-e7cfe77e116f.png)

**Comment by mdastro** [comment]
Just another comment, I realized this happens also to another spectrum when I zoom in it. It's not that bad, but it happens too.
![2231 53816 545_jpas](https://user-images.githubusercontent.com/10452764/27764711-c570bd62-5e76-11e7-9c92-9b3064f41ce0.png)
![1665 52976 514_jpas](https://user-images.githubusercontent.com/10452764/27764710-c56ef7ca-5e76-11e7-8c12-aa6f2de13516.png)

**Comment by pllim** [comment]
For your power-law spectra, `extrap` is not accurate enough (remember that `extrap` assumes the flux to be constant based on nearest point). For example, if your flux is 1e-18 FLAM at 3000 Angstrom and you don't have data at wavelength shorter than that, `extrap` would set the flux to 1e-18 FLAM for all wavelength `< 3000` Angstrom. This is obviously wrong for a power-law spectrum, and will underestimate the photometry. `extrap` is probably a bit misleading since it is not "real" extrapolation (if I could rename it, would have called it `nearest`).

There are several things you can do here:

1. As I have said before, find real data of that object to fill in the missing flux regions.
2. Use a model (e.g., a theoretical power-law spectrum) that closely resembles your object, not the file you are using.
3. Manually insert "fake" data points in your file so spectrum does not have to be extrapolated.

Your case for https://user-images.githubusercontent.com/10452764/27764710-c56ef7ca-5e76-11e7-8c12-aa6f2de13516.png should have worked though. If you want, you can provide *that* spectrum and a "bad" filter for it.

**Comment by mdastro** [comment]
Hi @pllim ,

I spent the last 2 weeks making tests and discussing with my supervisor about the best approach to this problem. I am still doing some tests and haven't found the best way around it, but I believe this doesn't make part of this issue anymore, so I am closing it. If it's the case, I will open a new issue.

Thank you for your time and help, I really appreciate it.

Cheers,

Malu

**Comment by pllim** [comment]
Hi, Malu. Thank you for letting me know. Best of luck in your research.
