### ISSUE TITLE
Producing warning message each time extrapolation is attempted on a parameterized keyword with EXTRAP=False

### ISSUE THREAD

**Issue by ndmiles** [spacetelescope/pysynphot#39]
Hey @pllim,

Quick use-case example of the issue:

```python
In [2]: bp =  S.ObsBandpass('acs,wfc1,f555w,mjd#59910')
/Users/nmiles/miniconda3/envs/astroconda3/lib/python3.5/site-packages/pysynphot/spectrum.py:3128: UserWarning: Extrapolation not allowed, using default throughput for /grp/hst/cdbs/comp/acs/acs_wfc_ccd1_mjd_022_syn.fits[mjd#] warnings.warn(s, UserWarning)`
`In [3]: bp1 = S.ObsBandpass('acs,wfc1,f555w,mjd#57910')`
`In [4]: bp2 = S.ObsBandpass('acs,wfc1,f555w,mjd#59910')`
`In [5]: bp3 = S.ObsBandpass('acs,wfc1,f555w,mjd#59909')
/Users/nmiles/miniconda3/envs/astroconda3/lib/python3.5/site-packages/pysynphot/spectrum.py:3128: UserWarning: Extrapolation not allowed, using default throughput for /grp/hst/cdbs/comp/acs/acs_wfc_ccd1_mjd_022_syn.fits[mjd#]
  warnings.warn(s, UserWarning)
```

The issue is that I am trying to use warnings raised by pynsynphot to notify users that the date they have entered does not fall in the ranges covered in the corresponding lookup table, which would mean I wouldn't have to continually update the website with date-ranges every time a new table is delivered.

I tried to remedy this problem by setting up a filter to always display warning messages falling in the UserWarning category,
```python
import warnings
warnings.filterwarnings('always', category=UserWarning)
```
and then including a context manager where I am testing the validity of the input date,
```python
with warnings.catch_warnings():
        warnings.filterwarnings('error', category=UserWarning)
```

From the above use-case example code you can see the pysynphot only displays the warning message **once per obsmode string**, so this will work provided a different obsmode string is submitted every time. If you want to see this in action, feel free to look at the repo https://grit.stsci.edu/nmiles/ZeropointApp and checkout the error_handling branch.

Lastly, I also tried `warnings.resetwarnings()`, but as per [http://bugs.python.org/issue21724](http://bugs.python.org/issue21724) this won't reset the global warning registry and instead only resets the local one for my program (which doesnt include the warning registry for pysynphot). Let me know if there is anything else you need!

**Comment by pllim** [comment]
You are in luck.
```python
>>> import pysynphot as S
>>> bp = S.ObsBandpass('acs,wfc1,f555w,mjd#59910')
>>> bp.warnings   # Has warnings
{'DefaultThroughput': True}
>>> bp2 = S.ObsBandpass('acs,wfc1,f555w')
>>> bp2.warnings  # No warnings
{}
```
