### ISSUE TITLE
FileSpectrum does not understand physical flux units

### ISSUE THREAD

**Issue by dhomeier** [spacetelescope/pysynphot#42]
Apparently `pysynphot` is supposed to be compatible with `astropy`, yet it does not accept FITS files in any flux "units" other than `'Flam'`, which in turn is useless to `astropy`, or likely any units-aware FITS reader.

It would be near-trivial to at least add the corresponding canonical `astropy` `spectral flux density wav` units `'erg / (s cm2 Angstrom)'`, `'erg / (Angstroms cm2 s)'` to the `factory` keys in `units.py`; or with a little bit more code to (`try` to) import `astropy.units` to test for all compatible unit names.

Perhaps even better, unit parsing and optionally converting might be done directly in `_readFITS`.

**Comment by pllim** [comment]
No, not this package. Look for https://github.com/spacetelescope/synphot_refactor for Astropy units and models.

**Comment by dhomeier** [comment]
Do you happen to know if JWST ETC is going to accept real units?

**Comment by dhomeier** [comment]
Background of this is, I will have to provide a number of spectral models for JWST calibration and analysis, and as long as the only accepted value for `TUNIT2` is a string that is useless for most other applications and running against the recommendations of the [FITS standard](https://fits.gsfc.nasa.gov/standard30/fits_standard30aa.pdf) §4.3, this would effectively force me to maintain two copies of the spectral library with only a header keyword changed...

**Comment by pllim** [comment]
This is not the right place for ETC questions. Maybe @laidler can point us to the proper place for public requests.

**Comment by dhomeier** [comment]
Thanks, I'd appreciate that. Trying to check at the [JWST Forum](https://confluence.stsci.edu/display/JWSTDADF/JWST+Data+Analysis+Development+Forum) to find out what their strategy re. incompatible toolkit packages is.

**Comment by vglaidler** [comment]
Please submit questions regarding the JWST ETC at the JWST help desk, http://jwsthelp.stsci.edu. Thank you.
