### ISSUE TITLE
Count rate with range computes sum that exceeds total count rate

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pysynphot#43]
As reported by @ibusko ...

*... large discrepancies affects the computation of the filter leak by the ETC. This leak is defined in terms of two count rates. One is the count rate within a specified wavelength band (using observation.countrate(range=XXX)). The other is the total count rate obtained by integrating over the entire wavelength range (calling countrate() without the ‘range’ parameter). For example, using the following inputs to pysynphot:*

```
obsmode:  stis,fuvmama,mirror,F25NDQ2,MJD#58300.0822774
filter wavelength range: [1160.22, 12000.0]
spectrum: rn(icat(k93models,44500,0.0,5.0),box(2000.000000,1.),1e-10,flam)
```

*we get for the in-band count rate, and total band count rate, using the [old] pysynphot in the ETC:*
```
   inband_rate -  123650.49941623237
   total_rate     -  123650.49941623239
   total_leak     -  1.1102230246251565e-16
```

*and for the same in-band count rate, and total band count rate, using the new pysynphot:*
```
   inband_rate  -  123646.6985008621
   total_rate      -  123646.69850086207
   total_leak     -  -2.2204460492503131e-16
```
*Note that in this case with the new pysynphot the resultant filter leak is negative, which is clearly wrong.*

Note: The "old" pysynphot does not have changes after July 2016, including #18.

Solution: Replace `np.sum()` with a more accurate `math.fsum()`. Also, need to add a test.

```python
import pysynphot as S
bp = S.ObsBandpass('stis,fuvmama,mirror,F25NDQ2,MJD#58300.0822774')
sp = S.parse_spec('rn(icat(k93models,44500,0.0,5.0),box(2000.000000,1.),1e-10,flam)')
obs = S.Observation(sp, bp)
c_all = obs.countrate()
c_sub = obs.countrate(range=[1160.22, 12000.0])
assert c_sub <= c_all
```

**Comment by pllim** [comment]
I traced it to Numpy's `sum()` function/method. There is nothing I can do about it. Curious though -- Did you use same Numpy version in your test of "old" and "new"? I see the same negative leak with Numpy 1.13.1.

Basically it comes down to the following calculations within `countrate()`:
(a) Without range: `obs.binflux.sum()`
(b) With given range in your example: `obs.binflux[160:11001].sum()`

However, when I replaced the calculations with `math.fsum()`, I get consistent results, so I guess I should issue a bug fix to pysynphot to use `math.fsum()` and not `np.sum()`:
```python
    >>> math.fsum(obs.binflux)
    123646.69850086208
    >>> math.fsum(obs.binflux[160:11001])
    123646.69850086208
```

**Comment by pllim** [comment]
Note: See numpy/numpy#8632 -- Numpy claims it is not a bug...

**Comment by mcara** [comment]
@pllim instead of trying ``math.fsum`` try to increase the type of ``np.sum``. It can happen that ``obs.binflux`` has a "low" type such as ``np.float32`` and then ``numpy.sum()`` will use ``float32`` as an intermediate variable to accumulate the sum. In this case you should modify the code as this:

```python
    np.sum(obs.binflux, dtype=np.float64)
```
What is the type of ``obs.binflux`` when you observe the loss of accuracy?

**Comment by pllim** [comment]
Could be. I can check the type tomorrow. But why are you against fsum()?

**Comment by mcara** [comment]
I am quite confident that ``np.sum(obs.binflux, dtype=np.float64)`` is faster than ``math.fsum(obs.binflux)`` **if** the problem is in ``obs.binflux`` having ``np.float32`` type. In addition numpy's ``sum`` is more versatile in the sense of accepting ``axis`` argument (it may or may not be useful for your particular issue(s)). However, if ``obs.binflux`` is already ``np.float64`` then ``math.fsum()`` will likely be faster than ``np.sum(obs.binflux, dtype=np.float128)`` and more portable.

**Comment by pllim** [comment]
Thanks, @mcara ! That sounds a like good plan. Now I just need to find time... :)

**Comment by pllim** [comment]
So, turns out `obs.binflux.dtype` is already `dtype('float64')`, so the solution is still `math.fsum()`. For academic purpose, here is the result for `float128`:
```python
>>>np.sum(obs.binflux, dtype=np.float128)
123646.69850086208569
>>>np.sum(obs.binflux[160:11001], dtype=np.float128)
123646.69850086208568
```

**Comment by ibusko** [comment]
I tested this new fix over the entire set of pyetc engine test cases. It fixed the negative filter leak bug. Thanks for the speedy fix!

**Comment by pllim** [comment]
Good to hear. Thanks for checking!
