### ISSUE TITLE
Typo with InterpolatedSpectralElement's isAnalytic attribute

### ISSUE THREAD

**Issue by martinjohndyer** [spacetelescope/pysynphot#48]
```InterpolatedSpectralElement.__init__``` has the ```self.isAnalytic``` attribute written incorrectly as ```self.analytic``` (in ```spectrum.py```, line 3060).

It looks like this typo has been there since 2009 when the ```isAnalytic``` flag was initially added with 342f2860036c3e12d017ef48d0bfde4e93047240!

For the record I found this by trying to multiply together an ```InterpolatedSpectralElement``` and ```TabularSpectralElement```:

- tabular\*interpolated works 
- interpolated\*tabular fails

That's due to ```self.isAnalytic = component1.isAnalytic and component2.isAnalytic``` in ```CompositeSpectralElement.__init__```.

**Comment by pllim** [comment]
Can you please provide a fully functional snippet to reproduce your problem? No one has come across this problem for so many years, so this usage must be an edge case. Although I agree with you that it looks like a bug. Providing me with an example would save me some time and help with writing a test to ensure this never happens again. Thank you for your cooperation.

**Comment by martinjohndyer** [comment]
No worries, happy to help!

It's easy to test if you make an ```InterpolatedSpectralElement```. Based on [test/test_interp_band.py](https://github.com/spacetelescope/pysynphot/blob/master/pysynphot/test/test_interp_band.py):

```python
import os
from pysynphot.spectrum import InterpolatedSpectralElement
interp_val = 51252.0
filename = os.path.join(os.environ['PYSYN_CDBS'], 'comp', 'stis', 'stis_nm16_mjd_010_syn.fits[MJD#]')
spec = InterpolatedSpectralElement(filename, interp_val)
spec.isAnalytic
```
raises an ```AttributeError```.

**Comment by pllim** [comment]
Ah... now I know why no one else encountered it. When PySynphot chains through the throughput files in a given graph table, the first one is never interpolated (usually, it is the last element); Therefore, `component2.isAnalytic` is never executed if `component2` is an `InterpolatedSpectralElement` in the way that `obsmode` is written. Does this make sense? I'll submit a fix shortly.

**Comment by martinjohndyer** [comment]
Yes, actually that's exactly how I found it. For my own model I added an interpolated element to represent the atmosphere as a function of wavelength, which happened to come first in the list. If that just never happens for the HST files that would explain why it was undiscovered for so long!
