### ISSUE TITLE
Use separate package for extinction curve

### ISSUE THREAD

**Issue by karllark** [spacetelescope/pysynphot#54]
There are external packages that provide extinction curves for python.  One of these packages could be used instead of the numerical tables currently used.  
Pros: offload the updating of the extinction curves to the "community"
Cons: Less control of the provided curves (but could be mitigated by automated testing against existing numerical results?)

Possible packages I know of:
https://github.com/kbarbary/extinction
https://github.com/karllark/dust_extinction
https://github.com/eblur/dust

In the interest of full disclose: I'm responsible for the 2nd package that has the aspiration of being an astropy affiliated package.  The goals of my package are to provide dust extinction curves to the community **and** for use in dust extinction research (mine and others).  Feedback is always welcomed.

**Comment by pllim** [comment]
From a quick glance on all three packages, only `dust_extinction` package uses `astropy.modeling`; Is that a fair assessment? If so, that is the one I would choose to integrate with `synphot_refactor` as part of  spacetelescope/synphot_refactor#132 (not here in PySynphot) because that package also relies heavily on `astropy.modeling`.

c/c @hcferguson @larrybradley

**Comment by pllim** [comment]
Also I propose that we close this issue here as "won't fix" and move the discussion to spacetelescope/synphot_refactor#132 . Is that okay, @karllark ?

**Comment by karllark** [comment]
Sounds reasonable to me.

**Comment by karllark** [comment]
I agree that only the dust_extinction package uses the astropy.modeling framework.  I'm finding using this framework very powerful and useful.  I've also been using the astropy.units framework.  Very nice as well.

**Comment by pllim** [comment]
Moved to spacetelescope/synphot_refactor#132 .
