### ISSUE TITLE
Add support for all JWST filters

### ISSUE THREAD

**Issue by hover2pi** [spacetelescope/pysynphot#61]
I know one can manually add support for the JWST filters via the `FileBandpass` or `ArrayBandpass` classes [as described in the documentation](http://pysynphot.readthedocs.io/en/latest/bandpass.html#from-file), but I was wondering if there were plans to officially support them via CRDS like the HST filters. Thanks!

**Comment by pllim** [comment]
This has been discussed offline and the current recommendation is to submit your request to JWST ETC developers. c/c @vglaidler
