### ISSUE TITLE
Old TSR link is broken

### ISSUE THREAD

**Issue by pllim** [spacetelescope/pysynphot#65]
http://stsdas.stsci.edu/tsr/2009_01/ is no longer accessible. @SaraOgaz , sorry to let you know so late but I need those back online.

**Comment by SaraOgaz** [comment]
Is that really the only place we had our TSRs? @jhunkeler we should figure this out on Monday. Maybe we should put these up on github for now or something, since confluence isn't accessible to the public.  Or maybe I can have them put up on zope.

**Comment by pllim** [comment]
The unrendered source is at https://github.com/spacetelescope/pysynphot/tree/master/doc/tsrs , I think. I have never attempted to rebuild it before as it was published long before my time in the branch. And I doubt it would build nicely at first try now. If those rendered files are not too big, I can see if I can include them with the docs here. Thanks!

**Comment by jhunkeler** [comment]
@pllim there's a rogue build directory in there:
https://github.com/spacetelescope/pysynphot/tree/master/doc/tsrs/bandpar_comparison/build

:)

**Comment by pllim** [comment]
Well, what a pleasant(?) surprise. I'll have to think about how to have RTD include that in the official page. Thanks!

**Comment by pllim** [comment]
Update: `bandpar_comparison` is not the TSR I was looking for. Need to find another way to make them available again.
