### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by mileslucas** [spacetelescope/pysynphot#66]
Is there any plan to create a docker image for this package? Something with astroconda and python built in along with the CDBS files?

I have a version that I use for my current work [here](https://github.com/mileslucas/FitSED/blob/master/Dockerfile) but I don't know what guidelines STScI would have for it.

**Comment by pllim** [comment]
Hello. I see that you have also contacted us about this via ServiceNow. Let's move the conversation there unless you would prefer to discuss it publicly over here.

**Comment by pllim** [comment]
Feel free to re-open this if you would prefer the latter. Thanks.
