### ISSUE TITLE
Documentation (location of pysynphot reference files)

### ISSUE THREAD

**Issue by hcferguson** [spacetelescope/pysynphot#75]
I've been working through Brian York's draft of Pandeia documentation and ran across a few inconsistencies in the pointers to the location of the pysynphot reference files:

The readthedocs documentation says:

 ```Data files for pysynphot are distributed separately by Calibration Reference Data System.```

That takes you to the the Zope site for crds http://www.stsci.edu/hst/observatory/crds/throughput.html. Which says, partway down the page:

   ```Master tables (For the most up-to-date files in use by pysynphot please check here ):```

The target link for "here" is broken.

Further down on the Zope page, it does give an ftp address for downloading the gzipped tar files:  ftp://archive.stsci.edu/pub/hst/pysynphot/ . That works, but is different from the link given on the pysynphot readthedocs page (ftp.stsci.edu) which also works. This may not be a problem unless there is a chance of them getting out of sync. 

Having gone to the archive site first, I thought maybe the files were different versions and I only needed the latest. Going back to the readthedocs table I see that I need all 6. I'd recommending offering a package that has them all tarred together, as the default, and then letting people choose subsets if they want to save space.

**Comment by pllim** [comment]
`ftp.stsci.edu` is still valid and AFAIK is in sync, so RTD does not need update. All the other issues you mentioned will be handled separately by the RedCat Team, which is beyond the scope of this repository. Thanks for reporting this!

**Comment by pllim** [comment]
In #110 , I have replaced FTP with HTTP. There is nothing more I can do here. For problem with http://www.stsci.edu/hst/observatory/crds/throughput.html , please contact RedCat Team. They track their stuff somewhere on JIRA, I heard.
