### ISSUE TITLE
Can't reproduce Spectrum Manipulation results from tutorial - units problem?

### ISSUE THREAD

**Issue by vickyscowcroft** [spacetelescope/pysynphot#81]
Hi,

I've just started using pysynphot and I'm following the tutorials to get started. I'm working my way through and I've reached the 'Spectrum Manipulation' section, and I've hit a snag. I'm not sure if it's something I'm doing or a bug. 

I've been copying and pasting the code to make sure it's not a typo on my end, and I've tried using python 2.7 and 3.5. I'm using the astroconda release from STScI.

When I use the tutorial code as written, I can't reproduce the redshifted and renormalised spectra plot. Instead, the sp3 spectrum is much higher than the Vega spectrum:

<img width="580" alt="screenshot" src="https://user-images.githubusercontent.com/2481213/37465767-fdf165a4-2853-11e8-89a3-5b39a8479849.png">

If I change the units in renorm from flam to photlam this seems to fix the problem:

<img width="583" alt="screenshot" src="https://user-images.githubusercontent.com/2481213/37465815-15e56a0c-2854-11e8-884b-0d3f1cd66635.png">

But then the units aren't consistent with what was defined for the Vega spectrum at the start of the tutorial. Does that matter?

The other issue is the peak wavelength returned for the redshifted spectrum isn't the same as the value given in the tutorial (6182.9067 in the tutorial, vs 10997.0300 in my version). I think when I run it it may be evaluating a larger wavelength range and finding a peak wavelength further out? 

I've looked in the docs section to see if you have the code available for the tutorial but it's not there - rather just the rst files. Would it be possible to get the ipynb file to see what the difference is? I think that would be the quickest way to troubleshoot this. Perhaps some defaults were set when the tutorial was made.

Thanks,

Vicky

**Comment by pllim** [comment]
Good catch! This is a side effect of fixing #14. Since redshift is always calculated in PHOTLAM now, `sp2` has the unit of PHOTLAM instead of FLAM. I'll fix the documentation to correct this.

In the meantime, here is a Jupyter Notebook as you requested: https://gist.github.com/pllim/2fbd40ab12d5b3902f3d21f9a516ddbe

Given that you just started using this package, may I suggest that you switch to http://synphot.readthedocs.io/en/latest/ before it is too late? :smile: In the notebook, I also provided the same content using its own API, so you can see for yourself what it is capable of.

Thanks for reporting this!

**Comment by vickyscowcroft** [comment]
Brilliant, thank you!

I've grabbed the notebook and synphot and got it working.

FYI anyone else who comes across this - when I installed synphot it initially installed OK with conda, but then stopped jupyter notebook launching with the error: 

`AttributeError: module 'pkg_resources' has no attribute 'iter_entry_points'`

I fixed that by updating `setuptools` 

`conda install setuptools`

which installed `certifi` and updated `setuptools`, and now all seems to work well. 

It wasn't a huge problem - but it might save someone some googling :)

Thanks for getting back to me so quickly on this!

**Comment by pllim** [comment]
Thank you for letting us know. Just for completeness, what version was the old `setuptools` that caused you trouble?

**Comment by vickyscowcroft** [comment]
The old version of setuptools was 27.2.0-py35_0
It upgraded to 36.4.0-py35_1

**Comment by pllim** [comment]
Thank you!
