### ISSUE TITLE
'pip install pysynphot' does not work

### ISSUE THREAD

**Issue by annamurphree** [spacetelescope/pysynphot#90]
When I try to pip install this package, I keep getting this error:
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Anna\AppData\Local\Temp\pip-install-nilm8pmp\pysynphot\
The string after 'pip-install-' changes when I try again, but it will not install. Anybody have any tips? I've tried running it in pipenv. I am working in Windows.

**Comment by pllim** [comment]
Maybe permission issue? https://stackoverflow.com/questions/35991403/pip-install-returns-python-setup-py-egg-info-failed-with-error-code-1

**Comment by jhunkeler** [comment]
@annamurphree was that entire error? Maybe you have an old version of `pip`. The latest `pip` fails with an error message telling me it cannot import `numpy`, then exits `1`. In any case it looks like your environment does not have the required dependencies installed, so give this a try:

```cmd
x:\> conda create -n pysynphot python=3.6 astropy numpy cython
rem ^ cython included because I saw a warning that numpy+mkl wanted
rem  it during my test installation.
x:\> conda activate pysynphot
x:\> pip install pysynphot
```

**Comment by annamurphree** [comment]
![pysynerror](https://user-images.githubusercontent.com/39275460/40321446-b2c58f12-5cf4-11e8-9cc1-1d74151a6bc0.JPG)
@jhunkeler This is the error I got when I tried to conda create; it is the same one I keep getting. I've updated pip and setuptools; what do you think could be going wrong? Thank you!

**Comment by jhunkeler** [comment]
OK this is clearly a bug in the `relic` version control package. I'll work on fixing it, but in the meantime you might be able to work around this issue by installing `git` into the `pysynphot` environment using Conda:

```cmd
x:\> conda activate pysynphot
x:\> conda install git
```

**Comment by annamurphree** [comment]
![pysynerror1](https://user-images.githubusercontent.com/39275460/40323603-7f072788-5cfb-11e8-929b-1382a1933842.JPG)
@jhunkeler It let me install git into pysynphot, but now when I try to pip install pysynphot it gives me this error. Thank you for looking into this!

**Comment by jhunkeler** [comment]
@annamurphree Unfortunately the error isn't telling me much.

I suspect the failure was the result of trying to compile `pysynphot`'s C extensions without a compiler on your `%PATH%`. In order to build those extensions you will need to install Visual Studio Community Edition 2015 (or better).

https://www.visualstudio.com/vs/community/

**Comment by pllim** [comment]
@annamurphree , did Joe solve your problem yet?

I *think* that even if the C extension failed to compile, the rest of the package might still have installed (hard to tell since you did not provide the entire log). Try start a Python session and `import pysynphot`.

**Comment by pllim** [comment]
@annamurphree , we have not heard back from you, so I am closing this ticket now. Feel free to re-open if this is still a problem.
