### ISSUE TITLE
Normalization of countrate different with and without bins

### ISSUE THREAD

**Issue by LouisDesdoigts** [spacetelescope/pysynphot#97]
I am trying to use pysynphot to calculate broadband fluxes in photons/s for different aperture sizes.

I have noticed a bug in setting binned to True vs False, where if I use the default HST aperture size, it gives very similar results whether or not the data are binned; but if we change the aperture size, the unbinned countrate changes and the binned one doesn't. 

This seems like a bug - or are we trying to use a feature wrong?

Here is an example with a toy model of alpha Cen A and changing the aperture size between its normal value and 1 cm^2.
```
acenA = S.Icat('phoenix',5790,0.2,4.30)
acenA.convert('photlam')
band = S.ObsBandpass('acs,wfc1,f555w')
acenA_norm = acenA.renorm(-0.1,'vegamag',band)
obs = S.Observation(acenA_norm,band)

obs.primary_area = 1 # cm2  # comment or don't comment this and see how it changes
obs.initbinset()
obs.initbinflux()
print(obs.countrate(binned=False))
print(obs.countrate(binned=True))
```

**Comment by pllim** [comment]
Hello. The primary area of the observation is inherited via bandpass. The primary area used by the package as a whole is set via `S.refs.setref()`. This is what I would recommend for you to get the correct results:

```python
import pysynphot as S

# This would use the default area (HST)
band = S.ObsBandpass('acs,wfc1,f555w')
acenA = S.Icat('phoenix',5790,0.2,4.30)
acenA.convert('photlam')
acenA_norm = acenA.renorm(-0.1,'vegamag',band)
obs = S.Observation(acenA_norm,band)
print(obs.countrate(binned=False))
print(obs.countrate(binned=True))

# This would use the user-defined area
S.refs.setref(area=1)  # cm2
band = S.ObsBandpass('acs,wfc1,f555w')
obs = S.Observation(acenA_norm,band)
print(obs.countrate(binned=False))
print(obs.countrate(binned=True))
```

p.s. There is no need to manually call `obs.init...` methods.

For the record, here are my outputs for default area:
```python
>>> print(obs.countrate(binned=False))
21106408442.95829
>>> print(obs.countrate(binned=True))
21106415612.586494
```

Here is using 1 cm^2:
```python
>>> print(obs.countrate(binned=False))
466554.0608960777
>>> print(obs.countrate(binned=True))
466554.21937965695
```

And just in case you use Astropy and would like to do this calculations from [stsynphot](https://stsynphot.readthedocs.io/en/latest/), which is an extension of [synphot](https://synphot.readthedocs.io/en/latest/), it would be like this:

```python
>>> import stsynphot as stsyn
>>> from synphot import units, Observation
>>> band = stsyn.band('acs,wfc1,f555w')
>>> acenA = stsyn.grid_to_spec('phoenix', 5790, 0.2, 4.30)
>>> acenA_norm = acenA.normalize(-0.1*units.VEGAMAG, band, vegaspec=stsyn.Vega)
>>> obs = Observation(acenA_norm, band, binset=band.binset)
>>> obs.countrate(stsyn.conf.area)  # HST
<Quantity 2.11068296e+10 ct / s>
>>> obs.countrate(1 * units.AREA)
<Quantity 466563.37011093 ct / s>
```

If this has sufficiently addressed your question, please close the issue. Thank you!
